baseURL: 'https://raven-silvermoon.eu'
languageCode: 'en-gb'
title: 'Raven Silvermoon-EU'
theme: ["github.com/Mitrichius/hugo-theme-anubis"]
paginate: 10

menu:
  main:
  - identifier: home
    name: Home
    title: Home
    url: /
    weight: 1
  - identifier: blog
    name: Blog
    title: Blog
    url: /posts/
    weight: 2
  - identifier: about-us
    name: About Us
    title: About Us
    url: /about-us/
    weight: 3
  - identifier: progress
    name: Progress
    title: Progress
    url: /progress/
  - identifier: cookbook
    name: Raven Cookbook
    title: Raven Cookbook
    url: /cookbook.pdf

params:
  style: auto-without-switcher
  customCSS:
    - css/additional.css

markup:
  goldmark:
    renderer:
      unsafe: true
